# Generated by Django 3.2 on 2023-02-10 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='Required. 30 characters or fewer, startinf with a letter, Letters, Digits', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_\\.]+$', 'Enter a valid username starting with a-z.This value may contain only letters, numbersand underscore characters.', 'invalid')], verbose_name='username'),
        ),
    ]
