# Generated by Django 3.2 on 2023-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
